[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >= 61.0",
    "cython >= 3.0.10",
    "numpy"
]

[project]

name = "burst-lag"
version = "0.0"

requires-python = ">= 3.9.7"

dependencies = [
    "cython >= 3.0.10",
    "numpy >= 1.26.4",
]